In [26]:
import geopandas as gpd

In [29]:
demo_data_2020.gdf = gpd.read_file('2020_PHL_data.geojson')

C:\Users\Hello\.conda\envs\geospatial\lib\site-packages\geopandas\geodataframe.py:182: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  super(GeoDataFrame, self).__setattr__(attr, val)

demo_data_2020

In [30]:
demo_data_2020.head(n=5)

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,...,J_GEO_ID,J_NAME,J_total_pop,J_white_pop,J_black_pop,J_asian_pop,J_DECENNIALPL2020.P2_data_with_overlays_2021-11-29T140643_NAME,J_hisp_pop,J_non_hisp_pop,geometry
0,42,101,012204,42101012204,122.04,Census Tract 122.04,G5020,S,879459,56473,...,1400000US42101012204,"Census Tract 122.04, Philadelphia County, Penn...",3694,657,2628,149,"Census Tract 122.04, Philadelphia County, Penn...",155,3539,"MULTIPOLYGON (((2676981.178 254440.769, 267737..."
1,42,101,012203,42101012203,122.03,Census Tract 122.03,G5020,S,227696,0,...,1400000US42101012203,"Census Tract 122.03, Philadelphia County, Penn...",658,280,143,155,"Census Tract 122.03, Philadelphia County, Penn...",32,626,"MULTIPOLYGON (((2678861.975 255056.314, 267886..."
2,42,101,013602,42101013602,136.02,Census Tract 136.02,G5020,S,246812,0,...,1400000US42101013602,"Census Tract 136.02, Philadelphia County, Penn...",3776,3026,228,188,"Census Tract 136.02, Philadelphia County, Penn...",187,3589,"MULTIPOLYGON (((2686906.790 243645.714, 268699..."
3,42,101,034502,42101034502,345.02,Census Tract 345.02,G5020,S,1021734,0,...,1400000US42101034502,"Census Tract 345.02, Philadelphia County, Penn...",5928,3132,1171,924,"Census Tract 345.02, Philadelphia County, Penn...",407,5521,"MULTIPOLYGON (((2724650.476 284639.902, 272485..."
4,42,101,000902,42101000902,9.02,Census Tract 9.02,G5020,S,155167,0,...,1400000US42101000902,"Census Tract 9.02, Philadelphia County, Pennsy...",2842,1853,150,670,"Census Tract 9.02, Philadelphia County, Pennsy...",97,2745,"MULTIPOLYGON (((2694530.584 234145.037, 269453..."

In [36]:
demo_data_2020['%_white_20'] = (demo_data_2020.J_white_pop / demo_data_2020.J_total_pop)* 100

In [37]:
demo_data_2020.head(5)

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,...,J_NAME,J_total_pop,J_white_pop,J_black_pop,J_asian_pop,J_DECENNIALPL2020.P2_data_with_overlays_2021-11-29T140643_NAME,J_hisp_pop,J_non_hisp_pop,geometry,%_white_20
0,42,101,012204,42101012204,122.04,Census Tract 122.04,G5020,S,879459,56473,...,"Census Tract 122.04, Philadelphia County, Penn...",3694,657,2628,149,"Census Tract 122.04, Philadelphia County, Penn...",155,3539,"MULTIPOLYGON (((2676981.178 254440.769, 267737...",17.785598
1,42,101,012203,42101012203,122.03,Census Tract 122.03,G5020,S,227696,0,...,"Census Tract 122.03, Philadelphia County, Penn...",658,280,143,155,"Census Tract 122.03, Philadelphia County, Penn...",32,626,"MULTIPOLYGON (((2678861.975 255056.314, 267886...",42.553191
2,42,101,013602,42101013602,136.02,Census Tract 136.02,G5020,S,246812,0,...,"Census Tract 136.02, Philadelphia County, Penn...",3776,3026,228,188,"Census Tract 136.02, Philadelphia County, Penn...",187,3589,"MULTIPOLYGON (((2686906.790 243645.714, 268699...",80.137712
3,42,101,034502,42101034502,345.02,Census Tract 345.02,G5020,S,1021734,0,...,"Census Tract 345.02, Philadelphia County, Penn...",5928,3132,1171,924,"Census Tract 345.02, Philadelphia County, Penn...",407,5521,"MULTIPOLYGON (((2724650.476 284639.902, 272485...",52.834008
4,42,101,000902,42101000902,9.02,Census Tract 9.02,G5020,S,155167,0,...,"Census Tract 9.02, Philadelphia County, Pennsy...",2842,1853,150,670,"Census Tract 9.02, Philadelphia County, Pennsy...",97,2745,"MULTIPOLYGON (((2694530.584 234145.037, 269453...",65.200563

In [46]:
demo_data_2020['%_black_20'] = (demo_data_2020.J_black_pop / demo_data_2020.J_total_pop) * 100

In [47]:
demo_data_2020['%_asian_20'] = (demo_data_2020.J_asian_pop / demo_data_2020.J_total_pop) * 100

In [48]:
demo_data_2020['%_hispanic_20'] = (demo_data_2020.J_hisp_pop / demo_data_2020.J_total_pop) * 100

In [50]:
demo_data_2020.head(5)

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,...,J_hisp_pop,J_non_hisp_pop,geometry,%_white_20,%_black,%_asian,%_hispanic,%_black_20,%_asian_20,%_hispanic_20
0,42,101,012204,42101012204,122.04,Census Tract 122.04,G5020,S,879459,56473,...,155,3539,"MULTIPOLYGON (((2676981.178 254440.769, 267737...",17.785598,71.142393,4.033568,4.195994,71.142393,4.033568,4.195994
1,42,101,012203,42101012203,122.03,Census Tract 122.03,G5020,S,227696,0,...,32,626,"MULTIPOLYGON (((2678861.975 255056.314, 267886...",42.553191,21.732523,23.556231,4.863222,21.732523,23.556231,4.863222
2,42,101,013602,42101013602,136.02,Census Tract 136.02,G5020,S,246812,0,...,187,3589,"MULTIPOLYGON (((2686906.790 243645.714, 268699...",80.137712,6.038136,4.978814,4.952331,6.038136,4.978814,4.952331
3,42,101,034502,42101034502,345.02,Census Tract 345.02,G5020,S,1021734,0,...,407,5521,"MULTIPOLYGON (((2724650.476 284639.902, 272485...",52.834008,19.753711,15.587045,6.865722,19.753711,15.587045,6.865722
4,42,101,000902,42101000902,9.02,Census Tract 9.02,G5020,S,155167,0,...,97,2745,"MULTIPOLYGON (((2694530.584 234145.037, 269453...",65.200563,5.277973,23.574947,3.413089,5.277973,23.574947,3.413089

In [52]:
demo_data_2010 = gpd.read_file('2010_PHL_data.geojson')

In [53]:
demo_data_2010.head(3)

,OBJECTID,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,...,LOGRECNO,j_GEO_ID,j_NAME,j_total_pop,j_white_pop,j_black_pop,j_asian_pop,j_j_hisp_pop,j_j_non_hisp_pop,geometry
0,1,42,101,009400,42101009400,94,Census Tract 94,G5020,S,366717,...,10429,1400000US42101009400,"Census Tract 94, Philadelphia County, Pennsylv...",3827,28,3687,8,76,3751,"POLYGON ((2675023.571 238568.103, 2675197.201 ..."
1,2,42,101,009500,42101009500,95,Census Tract 95,G5020,S,319070,...,10430,1400000US42101009500,"Census Tract 95, Philadelphia County, Pennsylv...",3313,18,3180,4,66,3247,"POLYGON ((2673233.272 241423.146, 2673202.232 ..."
2,3,42,101,009600,42101009600,96,Census Tract 96,G5020,S,405273,...,10431,1400000US42101009600,"Census Tract 96, Philadelphia County, Pennsylv...",4238,78,4000,27,82,4156,"POLYGON ((2671036.958 239093.213, 2671047.736 ..."

In [54]:
demo_data_2010['%_white_10'] = (demo_data_2010.j_white_pop / demo_data_2010.j_total_pop) *100

In [55]:
demo_data_2010['%_black_10'] = (demo_data_2010.j_black_pop / demo_data_2010.j_total_pop) * 100

In [56]:
demo_data_2010['%_asian_pop_10'] = (demo_data_2010.j_asian_pop / demo_data_2010.j_total_pop) * 100

In [58]:
demo_data_2010['%_hispanic_pop_10'] = (demo_data_2010.j_j_hisp_pop / demo_data_2010.j_total_pop) *100

In [60]:
demo_data_2010.head(10)

,OBJECTID,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,...,j_black_pop,j_asian_pop,j_j_hisp_pop,j_j_non_hisp_pop,geometry,%_white_10,%_black_10,%_asian_pop_10,%_hispanic_pop,%_hispanic_pop_10
0,1,42,101,009400,42101009400,94,Census Tract 94,G5020,S,366717,...,3687,8,76,3751,"POLYGON ((2675023.571 238568.103, 2675197.201 ...",0.731644,96.341782,0.209041,1.985890,1.985890
1,2,42,101,009500,42101009500,95,Census Tract 95,G5020,S,319070,...,3180,4,66,3247,"POLYGON ((2673233.272 241423.146, 2673202.232 ...",0.543314,95.985512,0.120736,1.992152,1.992152
2,3,42,101,009600,42101009600,96,Census Tract 96,G5020,S,405273,...,4000,27,82,4156,"POLYGON ((2671036.958 239093.213, 2671047.736 ...",1.840491,94.384143,0.637093,1.934875,1.934875
3,4,42,101,013800,42101013800,138,Census Tract 138,G5020,S,341256,...,1828,19,73,1988,"POLYGON ((2690491.906 245300.504, 2690365.343 ...",6.162057,88.694808,0.921883,3.541970,3.541970
4,5,42,101,013900,42101013900,139,Census Tract 139,G5020,S,562934,...,3106,32,212,3552,"POLYGON ((2690570.211 245290.765, 2690550.929 ...",12.646121,82.518597,0.850159,5.632306,5.632306
5,6,42,101,014000,42101014000,140,Census Tract 140,G5020,S,439802,...,2306,120,172,2838,"POLYGON ((2693932.448 242720.688, 2694170.015 ...",14.584718,76.611296,3.986711,5.714286,5.714286
6,7,42,101,014100,42101014100,141,Census Tract 141,G5020,S,562132,...,1594,70,255,1839,"POLYGON ((2695124.107 242446.600, 2695434.678 ...",12.989494,76.122254,3.342884,12.177650,12.177650
7,8,42,101,014200,42101014200,142,Census Tract 142,G5020,S,789935,...,296,149,404,3166,"POLYGON ((2701907.045 239523.994, 2702617.489 ...",79.131653,8.291317,4.173669,11.316527,11.316527
8,9,42,101,014300,42101014300,143,Census Tract 143,G5020,S,570015,...,66,53,103,1336,"POLYGON ((2705245.447 242376.925, 2704907.393 ...",87.004864,4.586518,3.683113,7.157748,7.157748
9,10,42,101,014400,42101014400,144,Census Tract 144,G5020,S,609439,...,589,63,1146,1959,"POLYGON ((2701140.617 242337.991, 2701248.783 ...",55.587762,18.969404,2.028986,36.908213,36.908213

In [61]:
demo_data_2010.save("PHL_2010_final")

AttributeError: 'GeoDataFrame' object has no attribute 'save'

In [64]:
gpd.save_file(demo_data_2010, "PHL_data_2010_final.geojson")

AttributeError: module 'geopandas' has no attribute 'save_file'

In [65]:
import fiona

In [68]:
demo_data_2010.to_file("PHL_2010_data_final.geojson", driver='GeoJSON')

In [69]:
demo_data_2020.to_file("PHL_2020_data_final.geojson", driver= 'GeoJSON')

In [5]:
import tobler as tob
from tobler import area_weighted
import geopandas as gpd

In [6]:
phl_2010 = gpd.read_file("2010_final.geojson")

In [7]:
phl_2020 = gpd.read_file("2020_final.geojson")

In [13]:
intensive_var = ['%_white_10','%_black_10', '%_asian_pop_10', '%_hispanic_pop_10' ]
extensive_var = ['j_total_pop_10']

In [14]:
areal_int_est = tob.area_weighted.area_interpolate(phl_2010, 
                                     phl_2020, 
                                     extensive_variables = extensive_var, 
                                     intensive_variables= intensive_var,
                                     allocate_total = True)

C:\Users\Hello\.conda\envs\geospatial\lib\site-packages\tobler\util\util.py:28: UserWarning: nan values in variable: %_hispanic_pop_10, replacing with 0
  warn(f"nan values in variable: {column}, replacing with 0")

In [15]:
areal_int_est.head(10)

,j_total_pop_10,%_white_10,%_black_10,%_asian_pop_10,%_hispanic_pop_10,geometry
0,3549.295044,26.266513,66.678368,3.253847,2.610450,"MULTIPOLYGON (((2676981.178 254440.769, 267737..."
1,1120.858310,40.891273,30.432185,22.701014,3.314963,"MULTIPOLYGON (((2678861.975 255056.314, 267886..."
2,3502.991077,84.183218,8.596764,3.770436,3.846793,"MULTIPOLYGON (((2686906.790 243645.714, 268699..."
3,5234.491627,67.813636,16.312087,9.197925,7.622686,"MULTIPOLYGON (((2724650.476 284639.902, 272485..."
4,2770.508682,67.472658,6.197437,23.010841,4.038192,"MULTIPOLYGON (((2694530.584 234145.037, 269453..."
5,3829.058602,87.618205,2.555377,6.449605,3.882253,"MULTIPOLYGON (((2686968.389 234057.379, 268738..."
6,3563.540810,90.531865,3.668736,2.856662,4.167358,"MULTIPOLYGON (((2696816.673 226287.830, 269683..."
7,3589.112798,3.621368,90.017043,1.735103,3.903121,"MULTIPOLYGON (((2695581.457 264515.135, 269560..."
8,4462.317946,86.353972,5.646649,3.607911,4.616482,"MULTIPOLYGON (((2736663.875 280506.242, 273682..."
9,2098.456275,6.410220,87.419055,1.724492,3.345682,"MULTIPOLYGON (((2686607.766 230418.596, 268662..."

In [16]:
areal_int_est.to_file('working_doc.geojson', driver = 'GeoJSON')

In [17]:
test = gpd.read_file('try_again.geojson')

In [21]:
test.to_crs()

ValueError: Must pass either crs or epsg.

In [20]:
test.to_crs(espg = '')

TypeError: to_crs() got an unexpected keyword argument 'espg'

In [22]:
test.set_crs()

ValueError: Must pass either crs or epsg.